# Generated by Django 6.1 on 2026-08-29 09:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('MEMBERSHIP', 'Membership'), ('SUPPORT', 'Club Support')], db_index=True, default='MEMBERSHIP', help_text='Purpose of the payment: membership or club support.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in Kenyan Shillings.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('method', models.CharField(choices=[('MPESA', 'M-Pesa')], db_index=True, default='MPESA', help_text='Payment method used for this transaction.', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current lifecycle state of the payment.', max_length=20)),
                ('phone_number', models.CharField(help_text='Normalized Kenyan phone number used for the M-Pesa STK Push.', max_length=20)),
                ('merchant_request_id', models.CharField(blank=True, help_text='Safaricom MerchantRequestID returned when the STK Push is initiated.', max_length=100, null=True, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, help_text='Safaricom CheckoutRequestID used to match the callback to this payment.', max_length=100, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='Official M-Pesa receipt number supplied by Safaricom after successful payment.', max_length=100, null=True, unique=True)),
                ('transaction_date', models.DateTimeField(blank=True, help_text='Transaction date and time reported by Safaricom.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time the payment was confirmed as completed.', null=True)),
                ('member', models.ForeignKey(help_text='KUCSA member associated with this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'status'], name='pay_member_status_idx'), models.Index(fields=['status', 'created_at'], name='pay_status_created_idx'), models.Index(fields=['member', 'created_at'], name='pay_member_created_idx'), models.Index(fields=['payment_type', 'status'], name='pay_type_status_idx'), models.Index(fields=['member', 'payment_type', 'created_at'], name='pay_mem_type_created')],
            },
        ),
    ]
