# Generated by Django 6.1 on 2026-08-29 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('members', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='financialauditlog',
            name='new_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='financialauditlog',
            name='old_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='financialcategory',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System categories are protected from normal modification or deactivation.'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='The original completed payment when this transaction originated from Payments.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_transaction', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOIDED', 'Voided')], default='DRAFT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['payment_source', 'expense_date'], name='finance_exp_payment_5fc088_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['category', 'transaction_date'], name='finance_fin_categor_15e9e2_idx'),
        ),
    ]
