# Generated by Django 6.1 on 2026-09-02 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expense_description_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='Original completed payment when this transaction originated from Payments.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_transaction', to='payments.payment'),
        ),
    ]
