# Generated by Django 6.1 on 2026-08-29 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(choices=[('EXECUTIVE', 'Executive Committee'), ('TECHNICAL', 'Technical Committee'), ('EVENTS', 'Events Committee'), ('FINANCE', 'Finance Committee'), ('COMMUNICATIONS', 'Communications Committee')], db_index=True, default='EXECUTIVE', help_text='Committee assigned to the executive.', max_length=30)),
                ('office_location', models.CharField(blank=True, help_text='Office or physical location of the executive.', max_length=150)),
                ('responsibilities', models.TextField(blank=True, help_text='Main responsibilities of the executive.')),
                ('vision', models.TextField(blank=True, help_text="Executive's vision for KUCSA.")),
                ('biography', models.TextField(blank=True, help_text='Short executive biography.')),
                ('term_start', models.DateField(blank=True, db_index=True, help_text='Date the executive term begins.', null=True)),
                ('term_end', models.DateField(blank=True, db_index=True, help_text='Date the executive term ends.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this executive profile is administratively active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User account associated with this executive profile.', on_delete=django.db.models.deletion.CASCADE, related_name='executive_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Executive',
                'verbose_name_plural': 'Executives',
                'ordering': ['user__first_name', 'user__last_name'],
                'indexes': [models.Index(fields=['committee', 'is_active'], name='exec_committee_active_idx'), models.Index(fields=['term_start', 'term_end'], name='exec_term_dates_idx'), models.Index(fields=['is_active', 'created_at'], name='exec_active_created_idx')],
            },
        ),
    ]
