# Generated by Django 6.1 on 2026-08-29 09:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('registration_number', models.CharField(blank=True, db_index=True, help_text='Official university registration number. Required for normal KUCSA student/member accounts but not required for administrative accounts.', max_length=50, null=True, unique=True, verbose_name='Registration Number')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Unique email address. Administrative accounts may exist without an email address.', max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number used for KUCSA communication and M-Pesa payments.', max_length=15, null=True, verbose_name='Phone Number')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('CHAIRPERSON', 'Chairperson'), ('VICE_CHAIRPERSON', 'Vice Chairperson'), ('SECRETARY', 'Secretary'), ('SECRETARY_GENERAL', 'Secretary General'), ('TREASURER', 'Treasurer'), ('ORGANIZING_SECRETARY', 'Organizing Secretary'), ('PUBLICITY_SECRETARY', 'Publicity Secretary'), ('ADMIN', 'Administrator')], db_index=True, default='STUDENT', help_text='Organizational role held by the user within KUCSA.', max_length=30, verbose_name='KUCSA Role')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text="Indicates whether the user's account has completed the required KUCSA verification process.", verbose_name='Account Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['role'], name='user_role_idx'), models.Index(fields=['is_verified'], name='user_verified_idx'), models.Index(fields=['role', 'is_verified'], name='user_role_verified_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
