# Generated by Django 6.1 on 2026-08-29 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Announcement Title')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated from the announcement title.', max_length=280, unique=True)),
                ('summary', models.CharField(blank=True, help_text='Short summary displayed on announcement lists, dashboard widgets and notification-style previews.', max_length=500)),
                ('content', models.TextField(verbose_name='Announcement Content')),
                ('announcement_type', models.CharField(choices=[('GENERAL', 'General'), ('EVENT', 'Event'), ('MEETING', 'Meeting'), ('ACADEMIC', 'Academic'), ('CAREER', 'Career Opportunity'), ('TRAINING', 'Training'), ('COMPETITION', 'Competition'), ('OPPORTUNITY', 'Opportunity'), ('REMINDER', 'Reminder'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], db_index=True, default='GENERAL', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Members'), ('STUDENTS', 'Students'), ('EXECUTIVES', 'Executives'), ('FIRST_YEARS', 'First Year Students'), ('SECOND_YEARS', 'Second Year Students'), ('THIRD_YEARS', 'Third Year Students'), ('FOURTH_YEARS', 'Fourth Year Students'), ('ALUMNI', 'Alumni')], db_index=True, default='ALL', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/images/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/attachments/')),
                ('published_at', models.DateTimeField(blank=True, help_text='Date and time when the announcement became visible to its target audience.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional date and time after which the announcement will no longer appear to members.', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Display this announcement prominently on the announcement page and dashboard.')),
                ('allow_comments', models.BooleanField(default=False, help_text='Allow members to comment on this announcement.')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement Read Record',
                'verbose_name_plural': 'Announcement Read Records',
                'ordering': ['-read_at'],
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'published_at'], name='announcemen_status_a4da61_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'expires_at'], name='announcemen_status_ade3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['announcement_type', 'status'], name='announcemen_announc_eccb99_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['priority', 'status'], name='announcemen_priorit_9a8f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['target_audience', 'status'], name='announcemen_target__089fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_featured', 'status'], name='announcemen_is_feat_3bba72_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['user', 'read_at'], name='announcemen_user_id_247868_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['user', 'announcement'], name='announcemen_user_id_bdf288_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementread',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_read_per_user'),
        ),
    ]
