# Generated by Django 6.1 on 2026-08-29 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(blank=True, db_index=True, help_text='Unique KUCSA membership number.', max_length=30, null=True, unique=True, verbose_name='Membership Number')),
                ('membership_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', help_text='Current KUCSA membership status.', max_length=20)),
                ('joined_date', models.DateField(blank=True, db_index=True, help_text='Date the member officially joined KUCSA.', null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, help_text='Date the current KUCSA membership expires.', null=True)),
                ('course', models.CharField(blank=True, help_text='Academic course or programme.', max_length=150)),
                ('year_of_study', models.PositiveSmallIntegerField(blank=True, help_text='Current year of study.', null=True)),
                ('bio', models.TextField(blank=True, help_text='Short description about the member.')),
                ('technical_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], db_index=True, default='BEGINNER', help_text='Current technical skill level.', max_length=20)),
                ('technical_domains', models.JSONField(blank=True, default=list, help_text='Technical domains such as Web Development, Cybersecurity, AI, Networking, Data Science, Cloud Computing, UI/UX, Mobile Development, etc.')),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of technical and professional skills.')),
                ('interests', models.JSONField(blank=True, default=list, help_text='List of member interests.')),
                ('github_url', models.URLField(blank=True, help_text="Member's GitHub profile.")),
                ('linkedin_url', models.URLField(blank=True, help_text="Member's LinkedIn profile.")),
                ('portfolio_url', models.URLField(blank=True, help_text="Member's portfolio website.")),
                ('is_profile_complete', models.BooleanField(db_index=True, default=False, help_text='Whether the member has completed their KUCSA profile.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User account associated with this KUCSA membership.', on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['user__first_name', 'user__last_name'],
                'indexes': [models.Index(fields=['membership_status', 'expiry_date'], name='member_status_expiry_idx'), models.Index(fields=['membership_status', 'created_at'], name='member_status_created_idx'), models.Index(fields=['technical_level'], name='member_technical_level_idx'), models.Index(fields=['course'], name='member_course_idx')],
            },
        ),
    ]
