# Generated by Django 6.1 on 2026-08-29 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Name of the attendance session.', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description or instructions for members.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', help_text='Current lifecycle status of the attendance session.', max_length=20)),
                ('opens_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when members can start marking attendance.', null=True)),
                ('closes_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when the attendance window closes.', null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Date and time when the attendance session was opened.', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Date and time when the attendance session was manually closed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, help_text='User who manually closed the attendance session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_attendance_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the attendance session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_sessions', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, help_text='User who opened/published the attendance session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], db_index=True, default='PENDING', help_text='Current attendance status.', max_length=20)),
                ('source', models.CharField(choices=[('SELF', 'Self Marked'), ('MANUAL', 'Manually Marked'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', help_text='How this attendance record was recorded.', max_length=20)),
                ('attendance_time', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when the member was recorded as present.', null=True)),
                ('marked_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when the current attendance status was recorded.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this attendance record.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, help_text='User who performed the attendance action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_marked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Member/student whose attendance is being recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Attendance session to which this record belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.attendancesession')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ('user__first_name', 'user__last_name', 'user__username', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['status', 'opens_at'], name='att_sess_status_open'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['status', 'closes_at'], name='att_sess_status_close'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['-created_at'], name='att_sess_created'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'status'], name='att_rec_sess_stat'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['user', 'status'], name='att_rec_user_stat'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['user', 'attendance_time'], name='att_rec_user_time'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['source', 'status'], name='att_rec_src_stat'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['-marked_at'], name='att_rec_marked'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_attendance_session_user'),
        ),
    ]
